import type { FlowContentRoute, ModeContentCategoryOwnership, ModeFlowStepDefinition } from '../../shared/modeFlowSchema';

export const SANDBOX_FLOW_DEFINITION: ModeFlowStepDefinition[] = [
  {
    mode: 'sandbox',
    stepId: 'PREHEAT_CHAT',
    stepPurpose: 'Bootstrap sandbox room with join logs and ambient preheat chat before tag ownership begins.',
    enterConditions: ['sandbox mode entered', 'bootstrap state present', 'introGate active'],
    exitConditions: ['preheat cadence completes or VIP tag step starts'],
    canReply: false,
    gateType: 'none',
    blockedReasons: ['bootstrap_not_ready', 'legacy_join_emitter_blocked'],
    uiSurface: ['chat_panel', 'review_packet'],
    nextStepCandidates: ['WAIT_WARMUP_REPLY', 'VIP_TAG_PLAYER'],
    allowedMessageCategories: ['sandbox_preheat'],
    messagePurpose: 'Establish sandbox room tone before player is directly addressed.',
    tonePack: 'sandbox_preheat',
    intensity: 'low',
    styleConstraints: [{ id: 'join-cap-safe', description: 'Preserve join-log cap / anti-flood assumptions.' }],
    selectionPolicy: 'variant_pool',
    notes: 'Owned by authored sandbox preheat sequence through appRuntimeContent adapter.',
    debugLabel: 'sandbox:preheat_chat'
  },
  {
    mode: 'sandbox',
    stepId: 'REVEAL_PROMPT',
    stepPurpose: 'Show the sandbox reveal prompt / consonant prompt before waiting for answer.',
    enterConditions: ['current prompt resolved', 'question/tag flow reached reveal prompt stage'],
    exitConditions: ['tag question emitted or wait-reply step armed'],
    canReply: false,
    gateType: 'reply_gate',
    blockedReasons: ['missing_current_prompt', 'render_sync_warning'],
    uiSurface: ['chat_panel', 'scene_overlay', 'review_packet'],
    nextStepCandidates: ['TAG_PLAYER_x', 'WAIT_REPLY_x'],
    allowedMessageCategories: ['sandbox_prompt'],
    messagePurpose: 'Expose the visible sandbox prompt text.',
    tonePack: 'sandbox_prompt',
    intensity: 'medium',
    styleConstraints: [{ id: 'keep-consonant-token', description: 'Keep {consonant} placeholder for prompt rendering.' }],
    selectionPolicy: 'runtime_adapter',
    notes: 'Reveal prompt template remains tokenized; shared question bank remains separate.',
    debugLabel: 'sandbox:reveal_prompt'
  },
  {
    mode: 'sandbox',
    stepId: 'WAIT_REPLY_x',
    stepPurpose: 'Authoritative sandbox answer gate for warmup or consonant reply.',
    enterConditions: ['replyGate armed', 'flow.step is WAIT_WARMUP_REPLY or WAIT_REPLY_x'],
    exitConditions: ['reply consumed into ANSWER_EVAL', 'help hint requested', 'blocked/timeout path'],
    canReply: true,
    gateType: 'reply_gate',
    blockedReasons: ['no_gate', 'gate_not_armed', 'can_reply_false', 'scene_not_synced_warning'],
    uiSurface: ['reply_bar', 'pinned_reply', 'chat_panel', 'debug_panel'],
    nextStepCandidates: ['HELP_HINT', 'ANSWER_EVAL'],
    allowedMessageCategories: ['sandbox_tag_question', 'sandbox_prompt', 'sandbox_debug_text'],
    messagePurpose: 'Hold the formal sandbox reply gate and player-facing ask.',
    tonePack: 'sandbox_wait_reply',
    intensity: 'medium',
    styleConstraints: [{ id: 'reply-gate-authority', description: 'Do not bypass authoritative replyGate ownership.' }],
    selectionPolicy: 'priority_then_optional',
    notes: 'Includes WAIT_WARMUP_REPLY compatibility and dynamic WAIT_REPLY_x path.',
    debugLabel: 'sandbox:wait_reply'
  },
  {
    mode: 'sandbox',
    stepId: 'HELP_HINT',
    stepPurpose: 'Emit sandbox help hint while keeping the same question active.',
    enterConditions: ['player asks for help/hint/unknown', 'current prompt still active'],
    exitConditions: ['hint shown and wait-reply remains armed', 'answer submitted later'],
    canReply: true,
    gateType: 'reply_gate',
    blockedReasons: ['missing_current_prompt', 'hint_source_missing'],
    uiSurface: ['chat_panel', 'reply_bar', 'review_packet'],
    nextStepCandidates: ['WAIT_REPLY_x', 'ANSWER_EVAL'],
    allowedMessageCategories: ['sandbox_help_hint'],
    messagePurpose: 'Provide image-memory or fallback hint without changing question ownership.',
    tonePack: 'sandbox_help_hint',
    intensity: 'low',
    styleConstraints: [{ id: 'keep-image-memory-token', description: 'Preserve {imageMemoryHint} token when used.' }],
    selectionPolicy: 'priority_then_optional',
    notes: 'Help hint text is sandbox-owned; memory hint data stays shared consonant tooling.',
    debugLabel: 'sandbox:help_hint'
  },
  {
    mode: 'sandbox',
    stepId: 'ANSWER_EVAL',
    stepPurpose: 'Evaluate sandbox answer and emit glitch/crowd reaction side content.',
    enterConditions: ['reply consumed from WAIT_REPLY_x', 'judge pipeline wrote lastReplyEval / audit'],
    exitConditions: ['answer evaluation committed', 'transition into REVEAL_WORD'],
    canReply: false,
    gateType: 'reply_gate',
    blockedReasons: ['judge_not_triggered', 'parse_failed', 'question_mismatch'],
    uiSurface: ['chat_panel', 'debug_panel', 'review_packet'],
    nextStepCandidates: ['REVEAL_WORD', 'VIP_SUMMARY_POST_REVEAL'],
    allowedMessageCategories: ['sandbox_glitch', 'sandbox_crowd_reaction'],
    messagePurpose: 'Short sandbox reaction burst around answer evaluation.',
    tonePack: 'sandbox_eval',
    intensity: 'high',
    styleConstraints: [{ id: 'keep-burst-short', description: 'Glitch/crowd reactions must stay short and bursty.' }],
    selectionPolicy: 'priority_then_optional',
    notes: 'sandbox_crowd_reaction is reserved for existing/parallel crowd-react sources.',
    debugLabel: 'sandbox:answer_eval'
  },
  {
    mode: 'sandbox',
    stepId: 'VIP_SUMMARY_POST_REVEAL',
    stepPurpose: 'Post-reveal VIP summary window after reveal completes.',
    enterConditions: ['reveal committed', 'post reveal chat stage active'],
    exitConditions: ['summary lines drained', 'advance-next becomes ready'],
    canReply: false,
    gateType: 'post_reveal_gate',
    blockedReasons: ['reveal_not_done', 'post_reveal_not_started'],
    uiSurface: ['chat_panel', 'scene_overlay', 'review_packet'],
    nextStepCandidates: ['ADVANCE_NEXT', 'TAG_QUESTION'],
    allowedMessageCategories: ['sandbox_vip_summary'],
    messagePurpose: 'Summarize learning step and bridge to next prompt.',
    tonePack: 'sandbox_vip_summary',
    intensity: 'medium',
    styleConstraints: [{ id: 'sequence-locked', description: 'Keep remember/pronounce/refer order intact.' }],
    selectionPolicy: 'variant_pool',
    notes: 'Maps VIP_SUMMARY_1/2 and post-reveal discussion ownership.',
    debugLabel: 'sandbox:vip_summary_post_reveal'
  },
  {
    mode: 'sandbox',
    stepId: 'TAG_QUESTION',
    stepPurpose: 'Tag the active user for the next sandbox question.',
    enterConditions: ['next question emitted', 'target user resolved'],
    exitConditions: ['tag line emitted', 'WAIT_REPLY_x armed'],
    canReply: false,
    gateType: 'reply_gate',
    blockedReasons: ['prompt_missing_for_tag', 'reply_source_missing'],
    uiSurface: ['chat_panel', 'reply_bar', 'review_packet'],
    nextStepCandidates: ['WAIT_REPLY_x'],
    allowedMessageCategories: ['sandbox_tag_question'],
    messagePurpose: 'Formal sandbox tag line that opens the next answer window.',
    tonePack: 'sandbox_tag',
    intensity: 'medium',
    styleConstraints: [{ id: 'keep-active-user-index', description: 'Preserve @activeUser and {index} tokens.' }],
    selectionPolicy: 'runtime_adapter',
    notes: 'Dynamic tag wrapper stays runtime-bound but text template is sandbox-owned.',
    debugLabel: 'sandbox:tag_question'
  },
  {
    mode: 'sandbox',
    stepId: 'DEBUG_SMOKE',
    stepPurpose: 'Sandbox smoke/debug helper text and legacy stubs used by tests or debug actions.',
    enterConditions: ['debug action or smoke test path running'],
    exitConditions: ['debug action completed or flow returns to owned step'],
    canReply: false,
    gateType: 'debug_gate',
    blockedReasons: ['debug_disabled', 'missing_runtime_stub'],
    uiSurface: ['debug_panel', 'chat_panel', 'review_packet'],
    nextStepCandidates: ['WAIT_REPLY_x', 'PREHEAT_CHAT', 'ANSWER_EVAL'],
    allowedMessageCategories: ['sandbox_debug_text', 'sandbox_stub'],
    messagePurpose: 'Stable debug-only or compatibility-only sandbox content.',
    tonePack: 'sandbox_debug',
    intensity: 'low',
    styleConstraints: [{ id: 'high-signal', description: 'Prefer stable identifiable strings over atmospheric prose.' }],
    selectionPolicy: 'debug_fixed',
    notes: 'Explicitly separates future-active debug copy from legacy/parallel stubs.',
    debugLabel: 'sandbox:debug_smoke'
  }
];

export const SANDBOX_FLOW_CONTENT_ROUTES: FlowContentRoute[] = [
  { mode: 'sandbox', stepId: 'PREHEAT_CHAT', allowedCategories: ['sandbox_preheat'], primaryCategory: 'sandbox_preheat', optionalCategories: [], messagePurpose: 'Preheat room setup.', tonePackSupport: true, tonePack: ['sandbox_preheat'], intensity: ['low'], styleConstraints: ['join-cap-safe'], runtimeSelectionPolicy: 'variant_pool', notes: 'Preheat sequence owned by authored sandbox content.' },
  { mode: 'sandbox', stepId: 'REVEAL_PROMPT', allowedCategories: ['sandbox_prompt'], primaryCategory: 'sandbox_prompt', optionalCategories: [], messagePurpose: 'Prompt / reveal copy.', tonePackSupport: true, tonePack: ['sandbox_prompt'], intensity: ['medium'], styleConstraints: ['keep-consonant-token'], runtimeSelectionPolicy: 'runtime_adapter', notes: 'Prompt text tokenized.' },
  { mode: 'sandbox', stepId: 'WAIT_REPLY_x', allowedCategories: ['sandbox_tag_question', 'sandbox_prompt', 'sandbox_debug_text'], primaryCategory: 'sandbox_tag_question', optionalCategories: ['sandbox_prompt', 'sandbox_debug_text'], messagePurpose: 'Formal ask + debug helper in wait-reply windows.', tonePackSupport: true, tonePack: ['sandbox_tag', 'sandbox_prompt'], intensity: ['medium'], styleConstraints: ['reply-gate-authority'], runtimeSelectionPolicy: 'priority_then_optional', notes: 'Warmup/debug compatibility included.' },
  { mode: 'sandbox', stepId: 'HELP_HINT', allowedCategories: ['sandbox_help_hint'], primaryCategory: 'sandbox_help_hint', optionalCategories: [], messagePurpose: 'Help hint.', tonePackSupport: true, tonePack: ['sandbox_help_hint'], intensity: ['low'], styleConstraints: ['keep-image-memory-token'], runtimeSelectionPolicy: 'priority_then_optional', notes: 'Shared hint data may be interpolated, but authored template is sandbox-owned.' },
  { mode: 'sandbox', stepId: 'ANSWER_EVAL', allowedCategories: ['sandbox_glitch', 'sandbox_crowd_reaction'], primaryCategory: 'sandbox_glitch', optionalCategories: ['sandbox_crowd_reaction'], messagePurpose: 'Evaluation reaction burst.', tonePackSupport: true, tonePack: ['sandbox_eval'], intensity: ['high'], styleConstraints: ['keep-burst-short'], runtimeSelectionPolicy: 'priority_then_optional', notes: 'Crowd reaction currently mostly parallel/stub territory.' },
  { mode: 'sandbox', stepId: 'VIP_SUMMARY_POST_REVEAL', allowedCategories: ['sandbox_vip_summary'], primaryCategory: 'sandbox_vip_summary', optionalCategories: [], messagePurpose: 'VIP recap.', tonePackSupport: true, tonePack: ['sandbox_vip_summary'], intensity: ['medium'], styleConstraints: ['sequence-locked'], runtimeSelectionPolicy: 'variant_pool', notes: 'Post-reveal bridge.' },
  { mode: 'sandbox', stepId: 'TAG_QUESTION', allowedCategories: ['sandbox_tag_question'], primaryCategory: 'sandbox_tag_question', optionalCategories: [], messagePurpose: 'Tag active user for next question.', tonePackSupport: true, tonePack: ['sandbox_tag'], intensity: ['medium'], styleConstraints: ['keep-active-user-index'], runtimeSelectionPolicy: 'runtime_adapter', notes: 'Dynamic tag text.' },
  { mode: 'sandbox', stepId: 'DEBUG_SMOKE', allowedCategories: ['sandbox_debug_text', 'sandbox_stub'], primaryCategory: 'sandbox_debug_text', optionalCategories: ['sandbox_stub'], messagePurpose: 'Debug/smoke messaging.', tonePackSupport: false, intensity: ['low'], styleConstraints: ['high-signal'], runtimeSelectionPolicy: 'debug_fixed', notes: 'sandbox_stub stays legacy/parallel compatibility.' }
];

export const SANDBOX_CONTENT_OWNERSHIP: ModeContentCategoryOwnership[] = [
  { mode: 'sandbox', category: 'sandbox_preheat', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Sandbox room warmup lines.', allowedStepIds: ['PREHEAT_CHAT'], tonePackSupport: true, tonePack: ['sandbox_preheat'], intensity: ['low'], styleConstraints: ['join flood safe', 'ambient only'], selectionPolicy: 'variant_pool' },
  { mode: 'sandbox', category: 'sandbox_prompt', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Sandbox reveal / prompt text.', allowedStepIds: ['REVEAL_PROMPT', 'WAIT_REPLY_x'], tonePackSupport: true, tonePack: ['sandbox_prompt'], intensity: ['medium'], styleConstraints: ['preserve {consonant}', 'do not move question bank into sandbox copy'], selectionPolicy: 'runtime_adapter' },
  { mode: 'sandbox', category: 'sandbox_help_hint', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Sandbox help hints.', allowedStepIds: ['HELP_HINT'], tonePackSupport: true, tonePack: ['sandbox_help_hint'], intensity: ['low'], styleConstraints: ['preserve {imageMemoryHint} when present'], selectionPolicy: 'priority_then_optional', notes: 'Shared consonant bank remains tooling-only data source.' },
  { mode: 'sandbox', category: 'sandbox_vip_summary', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'VIP recap lines after reveal.', allowedStepIds: ['VIP_SUMMARY_POST_REVEAL'], tonePackSupport: true, tonePack: ['sandbox_vip_summary'], intensity: ['medium'], styleConstraints: ['summary sequence fixed'], selectionPolicy: 'variant_pool' },
  { mode: 'sandbox', category: 'sandbox_glitch', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Short glitch burst during answer evaluation.', allowedStepIds: ['ANSWER_EVAL'], tonePackSupport: true, tonePack: ['sandbox_eval'], intensity: ['high'], styleConstraints: ['short burst only'], selectionPolicy: 'variant_pool' },
  { mode: 'sandbox', category: 'sandbox_tag_question', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Formal user tag / ask template.', allowedStepIds: ['WAIT_REPLY_x', 'TAG_QUESTION'], tonePackSupport: true, tonePack: ['sandbox_tag'], intensity: ['medium'], styleConstraints: ['preserve @activeUser', 'preserve {index}'], selectionPolicy: 'runtime_adapter' },
  { mode: 'sandbox', category: 'sandbox_debug_text', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Smoke-test and debug helper text.', allowedStepIds: ['WAIT_REPLY_x', 'DEBUG_SMOKE'], tonePackSupport: false, intensity: ['low'], styleConstraints: ['stable identifiable wording'], selectionPolicy: 'debug_fixed' },
  { mode: 'sandbox', category: 'sandbox_crowd_reaction', ownership: 'legacy_adapter', sourceStatus: 'parallel', messagePurpose: 'Crowd reaction placeholders around answer evaluation.', allowedStepIds: ['ANSWER_EVAL'], tonePackSupport: true, tonePack: ['sandbox_eval'], intensity: ['medium'], styleConstraints: ['compatibility only'], selectionPolicy: 'priority_then_optional', notes: 'Reserved for current/ future crowd-react registry; may still be stubbed.' },
  { mode: 'sandbox', category: 'sandbox_stub', ownership: 'legacy_adapter', sourceStatus: 'parallel', messagePurpose: 'Legacy runtime wrapper / stub-only sandbox text.', allowedStepIds: ['DEBUG_SMOKE'], tonePackSupport: false, intensity: ['low'], styleConstraints: ['do not promote to active entry without migration'], selectionPolicy: 'debug_fixed', notes: 'Parallel/runtime-wrapper-only sources remain compatibility layer, not future SSOT.' }
];
