import type { FlowContentRoute, ModeContentCategoryOwnership, ModeFlowStepDefinition } from '../../shared/modeFlowSchema';

export const CLASSIC_FLOW_DEFINITION: ModeFlowStepDefinition[] = [
  {
    mode: 'classic',
    stepId: 'EVENT_OPENER',
    stepPurpose: 'Classic event opens with a directed tagged line before reactions or QnA.',
    enterConditions: ['event registry selects a classic event', 'active user is available', 'event cooldown / pause checks pass'],
    exitConditions: ['opener line dispatched', 'event transaction committed or blocked'],
    canReply: false,
    gateType: 'event_gate',
    blockedReasons: ['locked_active', 'cooldown_blocked', 'no_active_user', 'registry_missing'],
    uiSurface: ['chat_panel', 'review_packet'],
    nextStepCandidates: ['EVENT_REACTION_WINDOW', 'QNA_ASKING', 'AMBIENT_ONLY'],
    allowedMessageCategories: ['event_dialog'],
    messagePurpose: 'Hook the player into a classic event thread.',
    tonePack: 'classic_event_tension',
    intensity: 'medium',
    styleConstraints: [
      { id: 'mention-active-user', description: 'Keep player-directed mention wrapper intact.' },
      { id: 'chat-length', description: 'Stay compatible with short chat bubble pacing.' }
    ],
    selectionPolicy: 'variant_pool',
    notes: 'Maps existing event opener/follow-up dialog pools without changing event engine ownership.',
    debugLabel: 'classic:event_opener'
  },
  {
    mode: 'classic',
    stepId: 'EVENT_REACTION_WINDOW',
    stepPurpose: 'Short reaction burst after event opener or effect.',
    enterConditions: ['event opener already emitted', 'reaction wave topic resolved'],
    exitConditions: ['reaction batch drained', 'window timeout or handoff to QnA/fallback'],
    canReply: false,
    gateType: 'event_gate',
    blockedReasons: ['reaction_pool_missing', 'event_exclusive_active'],
    uiSurface: ['chat_panel', 'review_packet'],
    nextStepCandidates: ['QNA_ASKING', 'AMBIENT_ONLY', 'FALLBACK_ONLY'],
    allowedMessageCategories: ['event_reaction', 'ambient_chat'],
    messagePurpose: 'Provide crowd reaction around the classic event beat.',
    tonePack: 'classic_crowd_reaction',
    intensity: 'medium',
    styleConstraints: [{ id: 'burst-short', description: 'Keep reactions as short bursts, not long explanations.' }],
    selectionPolicy: 'priority_then_optional',
    notes: 'Reuses existing event reaction pool plus optional ambient filler.',
    debugLabel: 'classic:event_reaction_window'
  },
  {
    mode: 'classic',
    stepId: 'QNA_ASKING',
    stepPurpose: 'Commit a classic QnA prompt into chat with wrapper metadata.',
    enterConditions: ['QNA flow started', 'question selected', 'question actor resolved'],
    exitConditions: ['question message committed', 'reply authority transferred to awaiting-reply state'],
    canReply: false,
    gateType: 'qna_gate',
    blockedReasons: ['question_send_failed', 'tag_not_sent', 'invalid_state'],
    uiSurface: ['chat_panel', 'review_packet'],
    nextStepCandidates: ['QNA_AWAITING_REPLY', 'QNA_ABORTED'],
    allowedMessageCategories: ['qna_prompt', 'fake_ai'],
    messagePurpose: 'Ask the current classic QnA step and expose options.',
    tonePack: 'classic_qna_prompt',
    intensity: 'medium',
    styleConstraints: [{ id: 'keep-options-wrapper', description: 'Preserve wrapper / option label structure.' }],
    selectionPolicy: 'runtime_adapter',
    notes: 'Actual chat wrapper still assembled in App.tsx runtime wrapper; this table marks ownership only.',
    debugLabel: 'classic:qna_asking'
  },
  {
    mode: 'classic',
    stepId: 'QNA_AWAITING_REPLY',
    stepPurpose: 'Classic reply bar is armed and player answer is awaited.',
    enterConditions: ['active QnA status is AWAITING_REPLY', 'questionMessageId exists'],
    exitConditions: ['player reply consumed', 'timeout escalation', 'manual abort'],
    canReply: true,
    gateType: 'reply_gate',
    blockedReasons: ['reply_gate_closed', 'question_message_missing', 'stalled_asking_timeout'],
    uiSurface: ['reply_bar', 'pinned_reply', 'chat_panel'],
    nextStepCandidates: ['QNA_RETRY_OR_UNKNOWN', 'QNA_RESOLVED', 'QNA_ABORTED'],
    allowedMessageCategories: ['qna_prompt', 'donate', 'ambient_chat'],
    messagePurpose: 'Keep focus on the active classic question while preserving compatible ambient traffic.',
    tonePack: 'classic_qna_wait',
    intensity: 'variable',
    styleConstraints: [{ id: 'reply-ui-visible', description: 'Reply UI remains owned by classic qna authoritative state.' }],
    selectionPolicy: 'priority_then_optional',
    notes: 'No runtime behavior change; used for ownership lookup and docs.',
    debugLabel: 'classic:qna_awaiting_reply'
  },
  {
    mode: 'classic',
    stepId: 'QNA_RETRY_OR_UNKNOWN',
    stepPurpose: 'Classic retry or unknown/help prompts after invalid or uncertain reply.',
    enterConditions: ['reply parsed as retry-needed or unknown/help'],
    exitConditions: ['retry prompt emitted', 'question re-asked', 'abort/resolution chosen'],
    canReply: true,
    gateType: 'reply_gate',
    blockedReasons: ['retry_limit_reached', 'question_missing'],
    uiSurface: ['chat_panel', 'reply_bar', 'review_packet'],
    nextStepCandidates: ['QNA_AWAITING_REPLY', 'QNA_RESOLVED', 'QNA_ABORTED'],
    allowedMessageCategories: ['qna_retry', 'qna_unknown'],
    messagePurpose: 'Clarify or retry the active classic QnA step.',
    tonePack: 'classic_qna_retry',
    intensity: 'medium',
    styleConstraints: [{ id: 'stay-on-question', description: 'Do not leave the current question scope.' }],
    selectionPolicy: 'variant_pool',
    notes: 'Covers retry and unknown prompt families from QNA_FLOWS.',
    debugLabel: 'classic:qna_retry_unknown'
  },
  {
    mode: 'classic',
    stepId: 'QNA_RESOLVED',
    stepPurpose: 'Classic QnA resolved successfully and reply gate closes.',
    enterConditions: ['markQnaResolved has committed outcome'],
    exitConditions: ['flow stops or returns to ambient/event state'],
    canReply: false,
    gateType: 'qna_gate',
    blockedReasons: ['none'],
    uiSurface: ['chat_panel', 'review_packet'],
    nextStepCandidates: ['AMBIENT_ONLY', 'EVENT_OPENER'],
    allowedMessageCategories: ['ambient_chat', 'fake_ai', 'donate'],
    messagePurpose: 'Release tension back into ambient classic chat after success.',
    tonePack: 'classic_release',
    intensity: 'low',
    styleConstraints: [{ id: 'no-reply-gate', description: 'Resolved state must not keep classic reply gate armed.' }],
    selectionPolicy: 'priority_then_optional',
    notes: 'Resolution surface remains runtime-owned; this records allowed content ownership.',
    debugLabel: 'classic:qna_resolved'
  },
  {
    mode: 'classic',
    stepId: 'QNA_ABORTED',
    stepPurpose: 'Classic QnA aborted due to timeout, manual stop, or invalid continuation.',
    enterConditions: ['markQnaAborted or stopQnaFlow invoked'],
    exitConditions: ['flow reset', 'ambient/fallback resumes'],
    canReply: false,
    gateType: 'qna_gate',
    blockedReasons: ['timeout', 'manual_abort', 'invalid_state'],
    uiSurface: ['chat_panel', 'review_packet'],
    nextStepCandidates: ['FALLBACK_ONLY', 'AMBIENT_ONLY', 'EVENT_OPENER'],
    allowedMessageCategories: ['fallback', 'ambient_chat'],
    messagePurpose: 'Gracefully leave a classic QnA branch without dangling reply ownership.',
    tonePack: 'classic_abort',
    intensity: 'low',
    styleConstraints: [{ id: 'short-recovery', description: 'Use short reset/fallback language only.' }],
    selectionPolicy: 'priority_then_optional',
    notes: 'Pairs with classic review-first boundary; no new import path added.',
    debugLabel: 'classic:qna_aborted'
  },
  {
    mode: 'classic',
    stepId: 'AMBIENT_ONLY',
    stepPurpose: 'Classic free-running ambient chat when no event or QnA owns the moment.',
    enterConditions: ['no active event or QnA gate owns chat'],
    exitConditions: ['new event opens', 'QnA starts', 'fallback reroll needed'],
    canReply: false,
    gateType: 'ambient_gate',
    blockedReasons: ['chat_auto_paused'],
    uiSurface: ['chat_panel', 'review_packet'],
    nextStepCandidates: ['EVENT_OPENER', 'QNA_ASKING', 'FALLBACK_ONLY'],
    allowedMessageCategories: ['ambient_chat', 'donate', 'fake_ai'],
    messagePurpose: 'Supply classic background chat from pooled content.',
    tonePack: 'classic_ambient',
    intensity: 'variable',
    styleConstraints: [{ id: 'pool-safe', description: 'Use only pooled classic ambient content or donate/fake_ai inserts.' }],
    selectionPolicy: 'variant_pool',
    notes: 'Preserves shared ChatPools tooling without moving classic copy into shared ownership.',
    debugLabel: 'classic:ambient_only'
  },
  {
    mode: 'classic',
    stepId: 'FALLBACK_ONLY',
    stepPurpose: 'Safe fallback line when other classic selection paths are blocked or linted.',
    enterConditions: ['safe fallback reroll requested', 'ambient/event/QnA content unavailable or blocked'],
    exitConditions: ['fallback line emitted', 'ambient resumes'],
    canReply: false,
    gateType: 'ambient_gate',
    blockedReasons: ['safe_pool_empty'],
    uiSurface: ['chat_panel', 'review_packet'],
    nextStepCandidates: ['AMBIENT_ONLY', 'EVENT_OPENER'],
    allowedMessageCategories: ['fallback'],
    messagePurpose: 'Guaranteed safe classic fallback content.',
    tonePack: 'classic_safe_fallback',
    intensity: 'low',
    styleConstraints: [{ id: 'lint-safe', description: 'Stay aligned with safe fallback pool / lint reroll usage.' }],
    selectionPolicy: 'single',
    notes: 'Shared UI shell may render it, but ownership stays classic/shared-fallback boundary.',
    debugLabel: 'classic:fallback_only'
  }
];

export const CLASSIC_FLOW_CONTENT_ROUTES: FlowContentRoute[] = [
  { mode: 'classic', stepId: 'EVENT_OPENER', allowedCategories: ['event_dialog'], primaryCategory: 'event_dialog', optionalCategories: [], messagePurpose: 'Classic event opener / follow-up line.', tonePackSupport: true, tonePack: ['classic_event_tension'], intensity: ['medium'], styleConstraints: ['mention-active-user'], runtimeSelectionPolicy: 'variant_pool', notes: 'Active event dialog pool.' },
  { mode: 'classic', stepId: 'EVENT_REACTION_WINDOW', allowedCategories: ['event_reaction', 'ambient_chat'], primaryCategory: 'event_reaction', optionalCategories: ['ambient_chat'], messagePurpose: 'Crowd reaction burst around event.', tonePackSupport: true, tonePack: ['classic_crowd_reaction'], intensity: ['medium'], styleConstraints: ['burst-short'], runtimeSelectionPolicy: 'priority_then_optional', notes: 'Event reactions primary; ambient only as optional fill.' },
  { mode: 'classic', stepId: 'QNA_ASKING', allowedCategories: ['qna_prompt', 'fake_ai'], primaryCategory: 'qna_prompt', optionalCategories: ['fake_ai'], messagePurpose: 'Ask current QnA prompt.', tonePackSupport: true, tonePack: ['classic_qna_prompt'], intensity: ['medium'], styleConstraints: ['keep-options-wrapper'], runtimeSelectionPolicy: 'runtime_adapter', notes: 'Runtime wrapper still owned by App + qna engine.' },
  { mode: 'classic', stepId: 'QNA_AWAITING_REPLY', allowedCategories: ['qna_prompt', 'donate', 'ambient_chat'], primaryCategory: 'qna_prompt', optionalCategories: ['donate', 'ambient_chat'], messagePurpose: 'Hold player attention while reply gate remains open.', tonePackSupport: true, tonePack: ['classic_qna_wait'], intensity: ['low', 'medium'], styleConstraints: ['reply-ui-visible'], runtimeSelectionPolicy: 'priority_then_optional', notes: 'Reply authority remains classic qna state.' },
  { mode: 'classic', stepId: 'QNA_RETRY_OR_UNKNOWN', allowedCategories: ['qna_retry', 'qna_unknown'], primaryCategory: 'qna_retry', optionalCategories: ['qna_unknown'], messagePurpose: 'Retry / unknown guidance.', tonePackSupport: true, tonePack: ['classic_qna_retry'], intensity: ['medium'], styleConstraints: ['stay-on-question'], runtimeSelectionPolicy: 'variant_pool', notes: 'Maps to retryPromptVariants / unknownPromptVariants.' },
  { mode: 'classic', stepId: 'QNA_RESOLVED', allowedCategories: ['ambient_chat', 'fake_ai', 'donate'], primaryCategory: 'ambient_chat', optionalCategories: ['fake_ai', 'donate'], messagePurpose: 'Resolved aftermath.', tonePackSupport: true, tonePack: ['classic_release'], intensity: ['low'], styleConstraints: ['no-reply-gate'], runtimeSelectionPolicy: 'priority_then_optional', notes: 'No explicit resolved message pool yet.' },
  { mode: 'classic', stepId: 'QNA_ABORTED', allowedCategories: ['fallback', 'ambient_chat'], primaryCategory: 'fallback', optionalCategories: ['ambient_chat'], messagePurpose: 'Abort recovery.', tonePackSupport: false, intensity: ['low'], styleConstraints: ['short-recovery'], runtimeSelectionPolicy: 'priority_then_optional', notes: 'Use fallback first, then ambient recovery.' },
  { mode: 'classic', stepId: 'AMBIENT_ONLY', allowedCategories: ['ambient_chat', 'donate', 'fake_ai'], primaryCategory: 'ambient_chat', optionalCategories: ['donate', 'fake_ai'], messagePurpose: 'Ambient free chat.', tonePackSupport: true, tonePack: ['classic_ambient'], intensity: ['low', 'medium', 'high'], styleConstraints: ['pool-safe'], runtimeSelectionPolicy: 'variant_pool', notes: 'Classic persona/system pools.' },
  { mode: 'classic', stepId: 'FALLBACK_ONLY', allowedCategories: ['fallback'], primaryCategory: 'fallback', optionalCategories: [], messagePurpose: 'Guaranteed safe fallback.', tonePackSupport: false, intensity: ['low'], styleConstraints: ['lint-safe'], runtimeSelectionPolicy: 'single', notes: 'Shared safe fallback pool.' }
];

export const CLASSIC_CONTENT_OWNERSHIP: ModeContentCategoryOwnership[] = [
  { mode: 'classic', category: 'event_dialog', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Classic directed event opener/follow-up lines.', allowedStepIds: ['EVENT_OPENER'], tonePackSupport: true, tonePack: ['classic_event_tension'], intensity: ['medium'], styleConstraints: ['mention active user', 'short chat bubble'], selectionPolicy: 'variant_pool', notes: 'Owned by classic event dialog registry.' },
  { mode: 'classic', category: 'event_reaction', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Classic crowd reactions after event beats.', allowedStepIds: ['EVENT_REACTION_WINDOW'], tonePackSupport: true, tonePack: ['classic_crowd_reaction'], intensity: ['medium'], styleConstraints: ['burst only'], selectionPolicy: 'variant_pool', notes: 'Owned by classic event reaction pool.' },
  { mode: 'classic', category: 'qna_prompt', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Classic question prompt variants.', allowedStepIds: ['QNA_ASKING', 'QNA_AWAITING_REPLY'], tonePackSupport: true, tonePack: ['classic_qna_prompt'], intensity: ['medium'], styleConstraints: ['option wrapper preserved'], selectionPolicy: 'runtime_adapter', notes: 'Wrapper record remains runtime_wrapper in manifest for final emitted line.' },
  { mode: 'classic', category: 'qna_retry', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Classic retry prompt variants.', allowedStepIds: ['QNA_RETRY_OR_UNKNOWN'], tonePackSupport: true, tonePack: ['classic_qna_retry'], intensity: ['medium'], styleConstraints: ['stay scoped to same question'], selectionPolicy: 'variant_pool' },
  { mode: 'classic', category: 'qna_unknown', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Classic unknown/help prompt variants.', allowedStepIds: ['QNA_RETRY_OR_UNKNOWN'], tonePackSupport: true, tonePack: ['classic_qna_retry'], intensity: ['medium'], styleConstraints: ['stay scoped to same question'], selectionPolicy: 'variant_pool' },
  { mode: 'classic', category: 'ambient_chat', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Classic ambient chat pool.', allowedStepIds: ['EVENT_REACTION_WINDOW', 'QNA_AWAITING_REPLY', 'QNA_RESOLVED', 'QNA_ABORTED', 'AMBIENT_ONLY'], tonePackSupport: true, tonePack: ['classic_ambient'], intensity: ['low', 'medium', 'high'], styleConstraints: ['chat pool only'], selectionPolicy: 'variant_pool', notes: 'Includes system/type/persona pools.' },
  { mode: 'classic', category: 'fallback', ownership: 'shared_tooling', sourceStatus: 'active', messagePurpose: 'Safe fallback pool used by classic selection/lint reroll.', allowedStepIds: ['QNA_ABORTED', 'FALLBACK_ONLY'], tonePackSupport: false, intensity: ['low'], styleConstraints: ['safe fallback only'], selectionPolicy: 'single', notes: 'Shared safe pool is tooling-level shared, not mode-specific authored copy.' },
  { mode: 'classic', category: 'donate', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Donation inserts used in classic ambient windows.', allowedStepIds: ['QNA_AWAITING_REPLY', 'QNA_RESOLVED', 'AMBIENT_ONLY'], tonePackSupport: false, intensity: ['medium'], styleConstraints: ['keep donation structure'], selectionPolicy: 'variant_pool' },
  { mode: 'classic', category: 'fake_ai', ownership: 'mode_specific', sourceStatus: 'active', messagePurpose: 'Fake AI suspense replies for classic chat.', allowedStepIds: ['QNA_ASKING', 'QNA_RESOLVED', 'AMBIENT_ONLY'], tonePackSupport: true, tonePack: ['classic_fake_ai'], intensity: ['medium'], styleConstraints: ['do not convert into shared ui'], selectionPolicy: 'variant_pool' }
];
